variable "project_name" {}
variable "environment" {}
variable "private_data_subnet_az1_id" {}
variable "private_data_subnet_az2_id" {}
variable "database-snapshot-identifier" {}
variable "database-instance-class" {}
variable "availability_zone_1" {}
variable "database-instance-identifier" {}
variable "multi-az-deployment" {}
variable "database_security_group_id" {}