variable "project_name" {}
variable "environment" {}
variable "public_subnet_az1_id" {}
variable "internet_gateway" {}
variable "public_subnet_az2_id" {}
variable "vpc_id" {}
variable "private_data_subnet_az1" {}
variable "availability_zone_1" {}
variable "private_app_subnet_az1_id" {}
variable "private_data_subnet_az2" {}
variable "private_app_subnet_az2_id" {}
variable "rivate_data_subnet_az1" {}